# Generated by Django 5.2 on 2025-04-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_foodorder_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='order_date',
        ),
    ]
